# 10 debug, 20 info, 30 warning, 40 error, 50 critical
log_level: 0
video: __FILENAME__
video_offset_start: __FRAME_OFFSET__
video_offset_end: __FRAME_OFFSET__
output_sub_video: __SOME_MP4__
output_sub_ocr: __SOME_JSON__

detection:
  # object detection
  batch_size: 10
  frozen_graph: "model/frozen_inference_graph.pb"
  threshold: 0.9
  min_box_matches: 25

  # bilateral filter
  bilateral_filter: True
  diameter: 11
  sigma_color: 75
  sigma_space: 75

  # gaussian blur
  gaussian_blur: True
  kernel_size: 7
  standard_deviation: 1

  # adaptive thresholding
  block_size: 3
  constant: 4

  # threshold for the black pixels
  threshold_pixel: 3

  # character width
  char_min_coeff: 0.7
  char_max_coeff: 1.0
  char_min_dist: 0

  # character grouping
  grp_min_coeff: 0.75
  grp_min_dist_coeff: 0.25

recognition:
  model: "model/model.yml"
  weights: "model/model-0.96.h5"
  dictionary: "model/dictionary.txt"
